export const exercises = [
  {
    muscle_group: "Abs",
    name: "Full Reverse Crunch",
    equipment: "body",
  },
  { muscle_group: "Abs", name: "Lying Hip Thrust", equipment: "body" },
  { muscle_group: "Abs", name: "Reverse Crunch", equipment: "body" },
  {
    muscle_group: "Abs",
    name: "Alternating Heel Touch",
    equipment: "body",
  },
  {
    muscle_group: "Abs",
    name: "Decline Sit-Up w/ Twist",
    equipment: "body",
  },
  {
    muscle_group: "Abs",
    name: "Seated Medicine Ball Twist",
    equipment: "other",
  },
  { muscle_group: "Abs", name: "Trunk Rotator", equipment: "body" },
  { muscle_group: "Abs", name: "Front Plank", equipment: "static" },
  { muscle_group: "Abs", name: "Side-Plank", equipment: "static" },
  { muscle_group: "Abs", name: "Ab Cycle", equipment: "body" },
  {
    muscle_group: "Abs",
    name: "Kneeling Ab Rollout",
    equipment: "body",
  },
  {
    muscle_group: "Abs",
    name: "Medicine Ball V-Up",
    equipment: "other",
  },
  { muscle_group: "Abs", name: "V-Up", equipment: "body" },
  { muscle_group: "Abs", name: "Weighted V-Up", equipment: "other" },
  { muscle_group: "Abs", name: "Crunch", equipment: "body" },
  { muscle_group: "Abs", name: "Decline Crunch", equipment: "body" },
  { muscle_group: "Abs", name: "Decline Sit-Up", equipment: "body" },
  { muscle_group: "Abs", name: "Sit-Up", equipment: "body" },
  { muscle_group: "Abs", name: "Weighted Crunch", equipment: "other" },
  { muscle_group: "Back", name: "Assisted Pull-Up", equipment: "machine" },
  {
    muscle_group: "Back",
    name: "Close-Grip Lat Pulldown",
    equipment: "machine",
  },
  { muscle_group: "Back", name: "Lat Pulldown", equipment: "machine" },
  { muscle_group: "Back", name: "Pull-Up", equipment: "body" },
  {
    muscle_group: "Back",
    name: "Reverse-Grip Lat Pullown",
    equipment: "machine",
  },
  { muscle_group: "Back", name: "Reverse-Grip Pull-Up", equipment: "body" },
  {
    muscle_group: "Back",
    name: "Wide-Grip Lat Pulldown",
    equipment: "machine",
  },
  { muscle_group: "Back", name: "Bent-Over  Row", equipment: "barbell" },
  {
    muscle_group: "Back",
    name: "Bent-Over Reverse-Grip  Row",
    equipment: "barbell",
  },
  { muscle_group: "Back", name: "Row", equipment: "machine" },
  { muscle_group: "Back", name: "One Arm  Row", equipment: "dumbbell" },
  { muscle_group: "Back", name: "Rope Cable Row", equipment: "machine" },
  { muscle_group: "Back", name: "Seated Cable Row", equipment: "machine" },
  { muscle_group: "Back", name: "Seated Row", equipment: "machine" },
  { muscle_group: "Back", name: "Single-Arm Cable Row", equipment: "machine" },
  { muscle_group: "Back", name: "Single-Arm  Row", equipment: "dumbbell" },
  {
    muscle_group: "Back ",
    name: "Single-Arm Lat Pulldown",
    equipment: "machine",
  },
  { muscle_group: "Back", name: "Standing Cable Row", equipment: "machine" },
  {
    muscle_group: "Back",
    name: "Standing Single-Arm Cable Row",
    equipment: "machine",
  },
  { muscle_group: "Biceps", name: "Alternating  Curl", equipment: "dumbbell" },
  {
    muscle_group: "Biceps",
    name: "Alternating Hammer Curl",
    equipment: "dumbbell",
  },
  { muscle_group: "Biceps", name: "Curl", equipment: "barbell" },
  { muscle_group: "Biceps", name: "Bicep Curl", equipment: "dumbbell" },
  { muscle_group: "Biceps", name: "Cable Curl", equipment: "machine" },
  {
    muscle_group: "Biceps",
    name: "Concentration  Curl",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Biceps",
    name: "Cross Body Hammer Curl",
    equipment: "machine",
  },
  { muscle_group: "Biceps", name: "Curl", equipment: "dumbbell" },
  { muscle_group: "Biceps", name: "Hammer Curl", equipment: "dumbbell" },
  { muscle_group: "Biceps", name: "Curl", equipment: "machine" },
  {
    muscle_group: "Biceps",
    name: "Overhead Double Biceps Cable Curl",
    equipment: "machine",
  },
  {
    muscle_group: "Biceps",
    name: "Overhead Rope Cable Curl",
    equipment: "machine",
  },
  { muscle_group: "Biceps", name: "Preacher  Curl", equipment: "barbell" },
  { muscle_group: "Biceps", name: "Preacher Cable Curl", equipment: "machine" },
  {
    muscle_group: "Biceps",
    name: "Preacher Single-Arm  Curl",
    equipment: "dumbbell",
  },
  { muscle_group: "Biceps", name: "Reverse Curl", equipment: "dumbbell" },
  { muscle_group: "Biceps", name: "Rope Cable Curl", equipment: "machine" },
  {
    muscle_group: "Biceps",
    name: "Seated Alternating Curl",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Biceps",
    name: "Seated Alternating Hammer Curl",
    equipment: "dumbbell",
  },
  { muscle_group: "Biceps", name: "Seated  Curl", equipment: "dumbbell" },
  { muscle_group: "Biceps", name: "Seated Hammer Curl", equipment: "dumbbell" },
  {
    muscle_group: "Biceps",
    name: "Single-Arm Cable Curl",
    equipment: "machine",
  },
  {
    muscle_group: "Biceps",
    name: "Single-Arm  Curl w/ Incline Bench",
    equipment: "dumbbell",
  },
  { muscle_group: "Calves", name: "Calf Raise", equipment: "barbell" },
  { muscle_group: "Calves ", name: "Calf Press", equipment: "machine" },
  { muscle_group: "Calves", name: "Calf Raise - Seated", equipment: "machine" },
  {
    muscle_group: "Calves",
    name: "Calf Raise - Standing",
    equipment: "machine",
  },
  { muscle_group: "Calves", name: "Calf Raise", equipment: "dumbbell" },
  {
    muscle_group: "Calves",
    name: "Single-Leg  Calf Raise",
    equipment: "dumbbell",
  },
  { muscle_group: "Calves", name: "Smith  Calf Raise", equipment: "machine" },
  { muscle_group: "Calves", name: "Seated Calf Raise", equipment: "machine" },
  {
    muscle_group: "Calves",
    name: "Seated Single-Leg Calf Raise",
    equipment: "machine",
  },
  {
    muscle_group: "Chest",
    name: "Alternating  Bench Press",
    equipment: "dumbbell",
  },
  { muscle_group: "Chest", name: "Bench Press", equipment: "barbell" },
  {
    muscle_group: "Chest",
    name: "Decline  Bench Press",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Chest",
    name: "Decline Smith  Bench Press",
    equipment: "machine",
  },
  { muscle_group: "Chest", name: "Bench Press", equipment: "dumbbell" },
  { muscle_group: "Chest", name: "Elevated Push-Up", equipment: "body" },
  {
    muscle_group: "Chest",
    name: "Incline Alternating  Bench Press",
    equipment: "dumbbell",
  },
  { muscle_group: "Chest", name: "Incline  Bench Press", equipment: "barbell" },
  {
    muscle_group: "Chest",
    name: "Incline  Bench Press",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Chest",
    name: "Incline Hammer  Bench Press",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Chest",
    name: "Incline Single-Arm  Bench Press",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Chest",
    name: "Incline Smith  Bench Press",
    equipment: "machine",
  },
  {
    muscle_group: "Chest",
    name: "Incline Twisting  Bench Press",
    equipment: "dumbbell",
  },
  { muscle_group: "Chest", name: "Kneeling Push-Up", equipment: "body" },
  { muscle_group: "Chest", name: "Push-Up", equipment: "body" },
  {
    muscle_group: "Chest",
    name: "Single-Arm  Bench Press",
    equipment: "dumbbell",
  },
  { muscle_group: "Chest", name: "Smith  Bench Press", equipment: "machine" },
  {
    muscle_group: "Chest",
    name: "Twisting  Bench Press",
    equipment: "dumbbell",
  },
  { muscle_group: "Chest", name: "Wide-Grip Push-Up", equipment: "body" },
  { muscle_group: "Chest", name: "Cable Crossover", equipment: "machine" },
  { muscle_group: "Chest", name: "Cable Chest Fly", equipment: "machine" },
  { muscle_group: "Chest", name: "Decline Chest Fly", equipment: "dumbbell" },
  { muscle_group: "Chest", name: "Chest Fly", equipment: "dumbbell" },
  { muscle_group: "Chest", name: "High Cable Crossover", equipment: "machine" },
  {
    muscle_group: "Chest",
    name: "Incline Cable Chest Fly",
    equipment: "machine",
  },
  { muscle_group: "Chest", name: "Incline Chest  Fly", equipment: "dumbbell" },
  { muscle_group: "Chest", name: "Low Cable Crossover", equipment: "machine" },
  { muscle_group: "Chest", name: "Pec Deck", equipment: "machine" },
  { muscle_group: "Legs", name: "Deadlift", equipment: "barbell" },
  { muscle_group: "Legs", name: "Leg Curl", equipment: "machine" },
  { muscle_group: "Legs", name: "Lying Leg Curl", equipment: "machine" },
  { muscle_group: "Legs", name: "Seated Leg Curl", equipment: "machine" },
  { muscle_group: "Legs", name: "Hack Squat", equipment: "barbell" },
  { muscle_group: "Legs", name: "Lunge", equipment: "barbell" },
  { muscle_group: "Legs", name: "Reverse Lunge", equipment: "barbell" },
  { muscle_group: "Legs", name: "Split Squat", equipment: "barbell" },
  { muscle_group: "Legs", name: "Squat", equipment: "barbell" },
  { muscle_group: "Legs", name: "Step-Up", equipment: "barbell" },
  { muscle_group: "Legs", name: "Walking Lunge", equipment: "barbell" },
  { muscle_group: "Legs", name: "Lunge", equipment: "dumbbell" },
  { muscle_group: "Legs", name: "Reverse Lunge", equipment: "dumbbell" },
  { muscle_group: "Legs", name: "Side Lunge", equipment: "dumbbell" },
  { muscle_group: "Legs", name: "Split Squat", equipment: "dumbbell" },
  { muscle_group: "Legs", name: "Step-Up", equipment: "dumbbell" },
  { muscle_group: "Legs", name: "Walking Lunge", equipment: "dumbbell" },
  { muscle_group: "Legs", name: "Lateral  Squat", equipment: "barbell" },
  { muscle_group: "Legs", name: "Lateral  Step-Up", equipment: "barbell" },
  { muscle_group: "Legs", name: "Leg Press", equipment: "machine" },
  { muscle_group: "Legs", name: "Lunge", equipment: "body" },
  { muscle_group: "Legs", name: "Hack Squat", equipment: "machine" },
  {
    muscle_group: "Legs",
    name: "Single-Arm  Side Squat",
    equipment: "barbell",
  },
  {
    muscle_group: "Legs",
    name: "Single-Arm  Side Squat",
    equipment: "dumbbell",
  },
  { muscle_group: "Legs", name: "Smith Machine  Squat", equipment: "machine" },
  { muscle_group: "Legs", name: "Leg Extension", equipment: "machine" },
  { muscle_group: "Legs", name: "Singe-Leg Leg Press", equipment: "machine" },
  { muscle_group: "Legs", name: "Front Squat", equipment: "barbell" },
  { muscle_group: "Legs", name: "Single-Leg Extension", equipment: "machine" },
  { muscle_group: "Lower Back", name: "Back Raise", equipment: "machine" },
  { muscle_group: "Lower Back", name: "Superman Hold", equipment: "static" },
  { muscle_group: "Shoulders", name: "Arnold  Press", equipment: "dumbbell" },
  { muscle_group: "Shoulders", name: "Over-head Press", equipment: "barbell" },
  {
    muscle_group: "Shoulders",
    name: "Alternating Shoulder Press",
    equipment: "dumbbell",
  },
  { muscle_group: "Shoulders", name: "Front Raise", equipment: "dumbbell" },
  { muscle_group: "Shoulders", name: "Over-head Press", equipment: "dumbbell" },
  { muscle_group: "Shoulders", name: "Shoulder Press", equipment: "machine" },
  {
    muscle_group: "Shoulders",
    name: "Single-Arm  Shoulder Press",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Shoulders",
    name: "Smith  Shoulder Press",
    equipment: "machine",
  },
  { muscle_group: "Shoulders", name: "Front Raise", equipment: "barbell" },
  {
    muscle_group: "Shoulders",
    name: "Bent-Over  Rear Delt Raise",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Shoulders",
    name: "Cable Front Raise",
    equipment: "machine",
  },
  {
    muscle_group: "Shoulders",
    name: "Cable Lateral Raise",
    equipment: "machine",
  },
  { muscle_group: "Shoulders", name: "Lateral Raise", equipment: "dumbbell" },
  {
    muscle_group: "Shoulders",
    name: "Lying  External Rotation",
    equipment: "dumbbell",
  },
  { muscle_group: "Shoulders", name: "Reverse Fly", equipment: "machine" },
  {
    muscle_group: "Shoulders",
    name: "Reverse Incline  Rear Delt Raise",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Shoulders",
    name: "Seated Lateral Raise",
    equipment: "machine",
  },
  {
    muscle_group: "Shoulders",
    name: "Single-Arm Cable Lateral Raise",
    equipment: "machine",
  },
  {
    muscle_group: "Shoulders",
    name: "Cable External Rotation",
    equipment: "machine",
  },
  {
    muscle_group: "Triceps",
    name: "Close-Grip Bench Press",
    equipment: "barbell",
  },
  { muscle_group: "Triceps", name: "Forward Lean Dips", equipment: "body" },
  { muscle_group: "Triceps", name: "Assisted Dips", equipment: "machine" },
  { muscle_group: "Triceps", name: "Diamond Push-Up", equipment: "body" },
  { muscle_group: "Triceps", name: "Dips", equipment: "body" },
  { muscle_group: "Triceps", name: "Dips", equipment: "machine" },
  { muscle_group: "Triceps", name: "Kickback", equipment: "dumbbell" },
  {
    muscle_group: "Triceps",
    name: "Lying Single-Arm  Triceps Extension",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Triceps",
    name: "Lying Tricep Extensions",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Triceps",
    name: "Overhead  Triceps Extension",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Triceps",
    name: "Overhead EZ-Bar Triceps Extension",
    equipment: "other",
  },
  {
    muscle_group: "Triceps",
    name: "Overhead Rope Cable Tricep Extension",
    equipment: "machine",
  },
  {
    muscle_group: "Triceps",
    name: "Overhead Single  Tricep Extension",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Triceps",
    name: "Overhead Single-Arm Cable Tricep Extension",
    equipment: "machine",
  },
  {
    muscle_group: "Triceps",
    name: "Overhead Single-Arm  Tricep Extension",
    equipment: "dumbbell",
  },
  {
    muscle_group: "Triceps",
    name: "Rope Tricep Pushdown",
    equipment: "machine",
  },
  {
    muscle_group: "Triceps",
    name: "Single-Arm Triceps Pushdown",
    equipment: "machine",
  },
  { muscle_group: "Triceps", name: "Tricep Extensions", equipment: "machine" },
  { muscle_group: "Triceps", name: "Tricep Pushdown", equipment: "machine" },
];
